import os
from PIL import Image, ImageDraw, ImageFont

# IT/개발 관련 키워드 풀 (Pexels 배경 검색용)
KEYWORD_POOL = ["coding", "technology", "artificial intelligence", "galaxy", "cyberpunk", "future city", "data", "space", "neon"]

def get_keyword_from_script(script_text):
    """대본 내용에 따라 가장 어울리는 배경 키워드를 자동 선택합니다."""
    keyword_map = {
        "AI": "artificial intelligence",
        "인공지능": "artificial intelligence",
        "우주": "galaxy",
        "데이터": "data",
        "알고리즘": "coding",
        "개발자": "coding",
        "인터넷": "technology",
        "미래": "future city",
    }
    for k, v in keyword_map.items():
        if k in script_text:
            return v
    import random
    return random.choice(KEYWORD_POOL)

def create_shorts_thumbnail(script_text, output_image_path="pipeline_frame.png", bg_image_path=None):
    """
    1080x1920 (9:16 숏폼 규격) 다크모드 카드뉴스 배경 프레임을 생성합니다.
    Pexels에서 다운받은 4K 배경 이미지가 있으면 그것을 배경으로 사용합니다.
    """
    width, height = 1080, 1920

    # Pexels 배경 이미지 사용 여부 분기
    using_photo = bg_image_path and os.path.exists(bg_image_path)
    if using_photo:
        base_img = Image.open(bg_image_path).convert("RGB")
        base_img = base_img.resize((width, height), Image.LANCZOS)
        image = base_img
        # 반투명 다크 오버레이 (가독성 향상) — 120으로 줄여서 사진이 잘 보이게
        overlay = Image.new("RGBA", (width, height), (10, 8, 20, 120))
        image = image.convert("RGBA")
        image = Image.alpha_composite(image, overlay).convert("RGB")
        print(f"🖼️ Pexels 4K 배경 이미지 적용 완료!")
    else:
        # 기본 딥 다크 퍼플 배경
        image = Image.new("RGB", (width, height), color=(15, 12, 29))

    draw = ImageDraw.Draw(image)

    # 상단 그래픽 장식 원 — 기본 배경일 때만 표시 (Pexels 사진과 겹치지 않게)
    if not using_photo:
        draw.ellipse([width//2 - 300, 80, width//2 + 300, 680], fill=(79, 70, 229, 60))

    # 기본 폰트
    try:
        font_title = ImageFont.truetype("arial.ttf", 65)
        font_body = ImageFont.truetype("arial.ttf", 50)
        font_tag = ImageFont.truetype("arial.ttf", 38)
    except IOError:
        font_title = ImageFont.load_default()
        font_body = ImageFont.load_default()
        font_tag = ImageFont.load_default()

    # 타이틀 텍스트
    draw.text((width // 2, 400), "💡 오늘의 1분 IT 지식", fill=(200, 150, 255), font=font_title, anchor="mm")

    # 흰 구분선
    draw.line([(100, 480), (980, 480)], fill=(255, 255, 255, 80), width=2)

    # 본문 자막 (줄바꿈)
    lines = []
    words = script_text.split(" ")
    current_line = ""
    for word in words:
        if len(current_line + word) > 13:
            lines.append(current_line.strip())
            current_line = word + " "
        else:
            current_line += word + " "
    lines.append(current_line.strip())

    y_offset = 600
    for line in lines:
        draw.text((width // 2, y_offset), line, fill=(255, 255, 255), font=font_body, anchor="mm")
        y_offset += 90

    # 하단 브랜딩 + 해시태그
    draw.text((width // 2, 1700), "#AI #IT지식 #Shorts", fill=(168, 85, 247), font=font_tag, anchor="mm")
    draw.text((width // 2, 1780), "🤖 Auto-generated by AI Pipeline", fill=(148, 163, 184), font=font_tag, anchor="mm")

    image.save(output_image_path)
    print(f"🖼️ 숏폼 프레임 이미지 생성 완료: {output_image_path}")

    return output_image_path

if __name__ == "__main__":
    create_shorts_thumbnail("컴퓨터 버그의 진짜 유래를 아시나요? 1947년 세계 최초의 버그는 진짜 나방이었습니다!")
